# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :Otus_PAM => {
        :box_name => "centos/7",
	:box_version => "1804.02",
        :ip_addr => '192.168.12.50'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end
          
          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh

	    bash -c "sed -i 's/^PasswordAuthentication.*$/PasswordAuthentication yes/' /etc/ssh/sshd_config && systemctl restart sshd.service"

	    useradd otususer && useradd otusadmin && groupadd admin_grp && usermod -a -G admin_grp otusadmin && usermod -a -G admin_grp vagrant
	    echo "1234" | passwd --stdin otusadmin && echo "1234" | passwd --stdin otususer
        
            sed -i '5i\account required pam_time.so' /etc/pam.d/login
            	    
	    echo 'login;*;!admin_grp;Wd' >> /etc/security/time.conf  
		
	    reboot	
	   	
          SHELL

      end
  end
end
